source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

use_frameworks!

# Enable for consuming public pod
#target 'SRCoreDataStack_Example'
#pod 'SRCoreDataStack', '~> 0.2'


# Enable for development pod
# It is a local dependency (updated for pod v1.0+)
target 'SRCoreDataStack_Example' do
    pod 'SRCoreDataStack', :path => '../'
end


target 'SRCoreDataStack_ExampleTests' do
    pod 'SRCoreDataStack', :path => '../'
end
